name: Med_gen_micros_params_original
phase: train
gpu_ids:
- 1
distributed: true
path:
  log: logs
  tb_logger: tb_logger
  results: results
  checkpoint: checkpoint
  resume_state: null
datasets:
  train:
    name: soilCT
    mode: LRHR
    dataroot: /home/jovyan/work/Datasets/Data/17K_889MICRO/train
    datatype: img
    l_resolution: 64
    r_resolution: 256
    batch_size: 8
    num_workers: 1
    use_shuffle: true
    data_len: 3
  val:
    name: soilVal
    mode: LRHR
    dataroot: /home/jovyan/work/ddpm_sr3_soil/eval_imgs
    datatype: img
    l_resolution: 64
    r_resolution: 256
    data_len: -1
model:
  which_model_G: sr3
  finetune_norm: false
  unet:
    in_channel: 2
    out_channel: 1
    inner_channel: 32
    channel_multiplier:
    - 1
    - 2
    - 4
    attn_res:
    - 4
    - 8
    res_blocks: 4
    dropout: 0.2
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 10000
      linear_start: 1.0e-08
      linear_end: 0.02
    val:
      schedule: linear
      n_timestep: 10000
      linear_start: 1.0e-08
      linear_end: 0.02
  diffusion:
    image_size: 256
    channels: 1
    conditional: true
train:
  n_iter: 1000000
  val_freq: 1000.0
  save_checkpoint_freq: 1000.0
  print_freq: 200
  optimizer:
    type: adam
    lr: 0.0001
  ema_scheduler:
    step_start_ema: 80000
    update_ema_every: 40000
    ema_decay: 0.9
wandb:
  project: Med_gen_micros_real
